object Versions {
    val playServicesVersion = "17.0.0"
    val legacySupportVersion = "1.0.0"
    val kotlinVersion = "1.3.41"
    val androidCoreVersion = "1.2.0"
    val gradleVersion = "3.4.2"
    val appcompatVersion = "1.1.0-rc01"
    val junitVersion = "4.13-beta-3"
    val androidxTestRunnerVersion = "1.3.0-alpha01"
    val espressoCoreVersion = "3.3.0-alpha01"
    val daggerVersion = "2.23.2"
    val retrofitVersion = "2.6.0"
    val okhttpVersion = "4.0.1"
    val recyclerViewVersion = "1.1.0-beta01"
    val rxAndroidVersion = "2.1.1"
    val rxJavaVersion = "2.2.3"
    val glideVersion = "4.9.0"
    val truthVersion = "1.0"
    val truthExtVersion = "1.3.0-alpha01"
    val mockKVersion = "1.9.3"
    val coreTestingVersion = "2.0.0"
    val materialVersion = "1.2.0-alpha01"
    val roomVersion = "2.2.1"
    val constraintLayout = "1.1.3"
    val crashlyticsVersion = "17.0.0"
    val firebaseConfigVersion = "19.1.4"
    val firebaseAnalyticsVersion = "17.4.1"
    val gradleVersionPluginVersion = "0.27.0"
    val googleServicesVersion = "4.3.3"
    val fabricVersion = "2.0.0-beta03"
    val navigationComponentVersion = "2.1.0"
    val timberVersion = "4.7.1"
    val gsonVersion = "2.8.6"

}